# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://hub.jupyter.org/helm-chart/
#
debug:
  enabled: true
hub:
  config:
    AzureAdOAuthenticator:
      client_id: <REPLACE WITH DETAILS FROM AZUREAD APP REGISTRATION>
      client_secret: <REPLACE WITH DETAILS FROM AZUREAD APP REGISTRATION>
      oauth_callback_url: https://<REPLACE WITH ROOT URL>/hub/oauth_callback
      tenant_id: <REPLACE WITH DETAILS FROM AZUREAD APP REGISTRATION>
      allow_all: true
    JupyterHub:
      authenticator_class: azuread
    KubeSpawner:
      k8s_api_request_timeout: 300
singleuser:
  image:
    # You should replace the "latest" tag with a fixed version from:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/HEAD/datascience-notebook/Dockerfile
    name: jupyter/datascience-notebook
    tag: x86_64-ubuntu-22.04
  # `cmd: null` allows the custom CMD of the Jupyter docker-stacks to be used
  # which performs further customization on startup.
  cmd: null
