#cloud-config
write_files:
  - content: |
      ${install_k3s_script}
    path: /tmp/install_k3s.sh
    permissions: '0777'
  - content: |
      ${jupyterhub_config}
    path: /root/jupyterhub_config.yaml
    permissions: '0777'
  - content: |
      ${install_jupyterhub_script}
    path: /root/install_jupyterhub.sh
    permissions: '0777'

package_update: true

packages:
  - qemu-guest-agent
  - bash-completion
  - vim
  - git

yum_repos:
  baseos:
    gpgcheck: false
    baseurl: "http://10.134.8.240:80//install/rhels9.2.0/x86_64/BaseOS"
  appstream:
    gpgcheck: false
    baseurl: "http://10.134.8.240:80//install/rhels9.2.0/x86_64/AppStream"

runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent.service
  - bash /tmp/install_k3s.sh

ssh_authorized_keys:
%{ for key in public_key_openssh ~}
  - ${key}
%{ endfor ~}
