name: Generate terraform docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@aeae0038ed47a547e0c0fca5c059d3335f48fb25 # v1.3.0
      with:
        working-dir: ./terraform
        recursive: true
        recursive-path: modules
        output-file: README.md
        output-method: inject
        template: |-
          <!-- BEGIN_TF_DOCS -->
          {{ .Content }}

          ---
          <!-- END_TF_DOCS -->
        git-push: "true"
